第一题
2. Set configuration context $ kubectl config use-context k8s Monitor the logs of Pod foobar and
 
Extract log lines corresponding to error file-not-found
Write them to /opt/KULM00201/foobar
Question weight 5%

>> kubectl config use-context k8s && kubectl logs foobar | grep file-not-found >> /opt/KULM00201/foobar
 
第二题
3. Set configuration context $ kubectl config use-context k8s
 
List all PVs sorted by name saving the full kubectl output to /opt/KUCC0010/my_volumes . Use kubectl’s own functionally for sorting the output, and do not manipulate it any further.
 
Question weight 3%

>> kubectl get pv --sort-by={.metadata.name}
 
第三题
4. Set configuration context $ kubectl config use-context k8s
 
Ensure a single instance of Pod nginx is running on each node of the kubernetes cluster where nginx also represents the image name which has to be used. Do no override any taints currently in place.
 
Use Daemonsets to complete this task and use ds.kusc00201 as Daemonset name. Question weight 3%

"""
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds.kusc00201
spec:
  template:
    metadata:
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
"""
 
第四题
5. Set configuration context $ kubectl config use-context k8s Perform the following tasks
 
Add an init container to lumpy--koala (Which has been defined in spec file /opt/kucc00100/pod-spec-KUCC00100.yaml)
The init container should create an empty file named /workdir/calm.txt
If /workdir/calm.txt is not detected, the Pod should exit
Once the spec file has been updated with the init container definition, the Pod should be created.
Question weight 7%

"""
spec:
  initContainers:
  - image: busybox
    name: init-busybox
    volumeMounts:
    - name:
      mountPath: '/workdir'
    command: ['sh','-c','touch','/workdir/calm.txt'] 
""" 

第五题
 
6. Set configuration context $ kubectl config use-context k8s
 
Create a pod named kucc4 with a single container for each of the following images running inside (there may be between 1 and 4 images specified): nginx + redis + memcached + consul

"""
apiVersion: v1
kind: Pod
metadata:
  name: fourcontainers
spec:
  containers:
  - image:nginx
    name: nginx
  - image
  -
  -
""" 
 
第六题
7. Set configuration context $ kubectl config use-context k8s Schedule a Pod as follows:
 
Name: nginx-kusc00101
Image: nginx
Node selector: disk=ssd
"""
metadata:
  name: nginx-kusc00101
spec:
  containers:
  - name: nginx
    image: nginxa
  nodeSelector:
    disk: ssd
"""
Question weight: 2%


 
第七题
8. Set configuration context $ kubectl config use-context k8s Create a deployment as follows
 
Name: nginx-app
Using container nginx with version 1.10.2-alpine
The deployment should contain 3 replicas
Next, deploy the app with new version 1.13.0-alpine by performing a rolling update and record that update.
 
Finally, rollback that update to the previous version 1.10.2-alpine
 
Question weight: 4%
 
 
第八题
9. Set configuration context $ kubectl config use-context k8s
 
Create and configure the service front-end-service so it’s accessible through NodePort and routes to the existing pod named front-end
 
Question weight: 4%
 
 
第九题
10. Set configuration context $ kubectl config use-context k8s Create a Pod as follows:
 
Name: jenkins
Using image: jenkins
In a new Kubenetes namespace named website-frontend
Question weight 3%
 
 
第十题
11. Set configuration context $ kubectl config use-context k8s Create a deployment spec file that will:
 
Launch 7 replicas of the redis image with the label: app_env_stage=dev
Deployment name: kual00201
Save a copy of this spec file to /opt/KUAL00201/deploy_spec.yaml (or .json)
 
When you are done, clean up (delete) any new k8s API objects that you produced during this task
 
Question weight: 3%
 
 
第十一题
12. Set configuration context $ kubectl config use-context k8s
 
Create a file /opt/KUCC00302/kucc00302.txt that lists all pods that implement Service foo in Namespace production.
 
The format of the file should be one pod name per line.
 
Question weight: 3%
 
第十二题
13. Set configuration context $ kubectl config use-context k8s Create a Kubernetes Secret as follows:
 
Name: super-secret
Credential: alice or username:bob
Create a Pod named pod-secrets-via-file using the redis image which mounts a secret named super-secret at /secrets
 
Create a second Pod named pod-secrets-via-env using the redis image, which exports credential as TOPSECRET
 
Question weight: 9%
 
 
第十三题
14. Set configuration context $ kubectl config use-context k8s Create a pad as follows:
 
Name: non-persistent-redis
Container image: redis
Named-volume with name: cache-control
Mount path: /data/redis
It should launch in the pre-prod namespace and the volume MUST NOT be persistent.
 
Question weight: 4%
 
 
第十四题
15. Set configuration context $ kubectl config use-context k8s Scale the deployment webserver to 6 pods
 
Question weight: 1%
 
第十五题
16. Set configuration context $ kubectl config use-context k8s
 
Check to see how many nodes are ready (not including nodes tainted NoSchedule) and write the number to /opt/nodenum
 
Question weight: 2%.
 
第十六题
17. Set configuration context $ kubectl config use-context k8s
 
From the Pod label name=cpu-utilizer, find pods running high CPU workloads and write the name of the Pod consuming most CPU to the file /opt/cpu.txt (which already exists)
 
Question weight: 2%
 
第十七题
18. Set configuration context $ kubectl config use-context k8s Create a deployment as follows
 
Name: nginx-dns
Exposed via a service: nginx-dns
Ensure that the service & pod are accessible via their respective DNS records
The container(s) within any Pod(s) running as a part of this deployment should use the nginx image
Next, use the utility nslookup to look up the DNS records of the service & pod and write the output to /opt/service.dns and /opt/pod.dns respectively.
 
Ensure you use the busybox:1.28 image(or earlier) for any testing, an the latest release has an unpstream bug which impacts thd use of nslookup.
 
Question weight: 7%
 
 
第十八题
19. No configuration context change required for this item
 
Create a snapshot of the etcd instance running at https://127.0.0.1:2379 saving the snapshot to the file path /data/backup/etcd-snapshot.db
 
The etcd instance is running etcd version 3.1.10
 
The following TLS certificates/key are supplied for connecting to the server with etcdctl

CA certificate: /opt/KUCM00302/ca.crt
Client certificate: /opt/KUCM00302/etcd-client.crt
Clientkey:/opt/KUCM00302/etcd-client.key
Question weight: 7%
 
第十九题
20. Set configuration context $ kubectl config use-context ek8s
 
Set the node labelled with name=ek8s-node-1 as unavailable and reschedule all the pods running on it.
 
Question weight: 4%
 
第二十题
21. Set configuration context $ kubectl config use-context wk8s
 
A Kubernetes worker node, labelled with name=wk8s-node-0 is in state NotReady . Investigate why this is the case, and perform any appropriate steps to bring the node to a Ready state, ensuring that any changes are made permanent.
 
Hints:
 
You can ssh to the failed node using $ ssh wk8s-node-0
You can assume elevated privileges on the node with the following command $ sudo -i
 
Question weight: 4%
 
 
第二十一题
22. Set configuration context $ kubectl config use-context wk8s
 
Configure the kubelet systemd managed service, on the node labelled with name=wk8s-node-1, to launch a Pod containing a single container of image nginx named myservice automatically. Any spec files required should be placed in the /etc/kubernetes/manifests directory on the node.
 
Hints:
 
You can ssh to the failed node using $ ssh wk8s-node-1
You can assume elevated privileges on the node with the following command $ sudo -i
 
Question weight: 4%
 
第二十二题
23. Set configuration context $ kubectl config use-context ik8s
考试给了个init-config文件，kubeadm init --config=init-defaults.yaml
 
第二十三题
24. Set configuration context $ kubectl config use-context bk8s
 
Given a partially-functioning Kubenetes cluster, identify symptoms of failure on the cluster. Determine the node, the failing service and take actions to bring up the failed service and restore the health of the cluster. Ensure that any changes are made permanently.
 
The worker node in this cluster is labelled with name=bk8s-node-0 Hints:
 
You can ssh to the relevant nodes using $ ssh $(NODE) where $(NODE) is one of bk8s-master-0 or bk8s-node-0
You can assume elevated privileges on any node in the cluster with the following command$ sudo -i
Question weight: 4%
 
第二十四题
25. Set configuration context $ kubectl config use-context hk8s
 
Creae a persistent volume with name app-config of capacity 1Gi and access mode ReadWriteOnce. The type of volume is hostPath and its location is /srv/app-config
 
Question weight: 3%
